### ISSUE TITLE
Attribute error with cupy 'set_printoptions'

### ISSUE THREAD

**Issue by obi1brownobi** [samrere/pytortto#1]
Good day, I wanted to run your code in Colab, but I get an error when importing.
Tried:
`import tortto as tt`
Received error:
> AttributeError: module 'cupy' has no attribute 'set_printoptions'

The error is coming from line 24 of `__init__.py` of tortto:
`cp.set_printoptions(precision=4)`

Regards.

**Comment by samrere** [comment]
Hi do you have a file called "cupy.py" in your working directory? If you do, delete it so the real cupy library can be imported.

**Comment by samrere** [comment]
Hi,

I can reproduce the error on colab. Thanks for raising this issue.

It seems that Google colab have preinstalled cupy-cuda111 version 9.4.0 which doesn't have set_printoptions. Please update cupy-cuda111 by running `pip install -U cupy-cuda111` and restart the runtime.

Edit: first run `!pip list | grep cupy` to get the exact name of cupy, it's "cupy-cuda111" on my side, then update it.

**Comment by obi1brownobi** [comment]
Thanks for the help! Your work is truly impressive.
Regards.
